### ISSUE TITLE
Improve testing for dockerbuilder

### ISSUE THREAD

**Issue by smothiki** [deis/dockerbuilder#88] opened 2016-08-10 17:21 UTC
As of now dockerbuilder is a part of full E2E test. But if we look at functionality here dockerbuilder only does two things in DEIS. Takes a tar file extracts the code, builds a docker container according to the Dockerfile and pushes the container to registry.
Any PR in dockerbuilder should or also do this test instead of running entire E2E suite.

refer deis/workflow-e2e#303

**Comment by bacongobbler** [comment] 2016-08-15 14:50
related #36

**Comment by bacongobbler** [comment] 2016-10-31 16:36
closing as a duplicate of #36.

**Closed as completed by bacongobbler** 2016-10-31 16:36 UTC
Labels: enhancement, help wanted, needs tests
